### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by FaroBoon** [nyash-qq/galaxy-plugin-poe#1]
I copied to the src files into the plugins/installed folder and was able to get it to show up as an integration in GOG2.0 but it would not run.  I checked the requirements file and copied the requirements from other integrations but it will only crash.

**Comment by into-the-intraverse** [comment]
I'll add user-friendly README once GLX fully supports this. Currently it lacks icons/images and does not handle achievements. You basically can only install/uninstall/launch game.

**Comment by FaroBoon** [comment]
Cool!  Thanks!

**Comment by ziplock9000** [comment]
It shouldn't be on the https://github.com/Mixaill/awesome-gog-galaxy list if it's not yet working.

**Comment by into-the-intraverse** [comment]
Done 21c2581f43e4ab9a78191ba0261411de794b58ae
