### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Movian** [nyash-qq/galaxy-plugin-poe#2]
Hey, 
follow the installation instructions but ran into a problem on 

inv test build install

I cloned the repo into 
C:\Users\movia\AppData\Local\GOG.com\Galaxy\plugins\installed\galaxy-plugin-poe-Git

I tried it both with and without the Git at the end of the folder but it looks like its running into a problem extracting something (I added the Git in case it was trying to  create the folder path that was already there)

```
File "C:\Users\movia\AppData\Local\GOG.com\Galaxy\plugins\installed\galaxy-plugin-poe-Git\tasks.py", line 8, in <module>
    from galaxy.tools import zip_folder_to_file
ModuleNotFoundError: No module named 'galaxy'
```
Here is a screenshot of the whole power shell window.

http://prntscr.com/ov5zq4

I restarted G 2.0 and confirmed it does not see the interface.

**Comment by Movian** [comment]
I have continued investigating and it looks like you are using galaxy tool shed?  https://galaxyproject.org/

I have installed

**pip install galaxy-tool-util**

but it's still not working so I am presuming I need to set up the tool shed with the zip_folder_to_file tool...  will keep working on this and post any info I find...

Seems like the install just needs to be updated with this additional pre-rec once I get it to figure out

~edit~

Looks like I needed to run **pip install galaxy-lib**  instead 

it now appears to find the needed module, however it is having an error perorming the actual action now that it has the module...

`  File "C:\Users\movia\AppData\Local\GOG.com\Galaxy\plugins\installed\galaxy-plugin-poe-Git\tasks.py", line 8, in <module>
    from galaxy.tools import zip_folder_to_file
ImportError: cannot import name 'zip_folder_to_file' from 'galaxy.tools' (c:\users\movia\appdata\local\programs\python\python37-32\lib\site-packages\galaxy\tools\__init__.py)
PS C:\Users\movia\AppData\Local\GOG.com\Galaxy\plugins\installed\galaxy-plugin-poe-Git>`

**Comment by flesyMeM** [comment]
> File "C:\Users\movia\AppData\Local\GOG.com\Galaxy\plugins\installed\galaxy-plugin-poe-Git\tasks.py", line 8, in <module> from galaxy.tools import zip_folder_to_file ImportError: cannot import name 'zip_folder_to_file' from 'galaxy.tools' (c:\users\movia\appdata\local\programs\python\python37-32\lib\site-packages\galaxy\tools\__init__.py) PS C:\Users\movia\AppData\Local\GOG.com\Galaxy\plugins\installed\galaxy-plugin-poe-Git>

Getting the exact same error output here, aside from the different user name obviously.

**Comment by into-the-intraverse** [comment]
Sorry, had this messed up. Should be fixed by now

**Comment by Movian** [comment]
Looks like this issue is resolved...  :) 

However, there is now a new issue which I will open a new ticket for :)
