### ISSUE TITLE
Plugin unintuitive install_game behaviour 

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [nyash-qq/galaxy-plugin-poe#4]
Hey,

I've started up the POE plugin without POE installed. After clicking 'Install' it prompted me with installation for the game. After i went through the installation steps the window closed and plugin still didn't report the game as installed for Galaxy Client.

![image](https://user-images.githubusercontent.com/48480506/66747730-828f4800-ee85-11e9-8e0a-7df01e7cc9a4.png)

Further clicking on 'Install' button results in this window popping up

![image](https://user-images.githubusercontent.com/48480506/66747192-3bed1e00-ee84-11e9-8f62-965cc13b9f72.png)

Restarting galaxy doesn't change the games status. Or the behaviour of the button.

[plugin-pathofexile-52d06761-1c23-d725-9720-57ee0b8b14bc.log](https://github.com/nyash-qq/galaxy-plugin-poe/files/3724175/plugin-pathofexile-52d06761-1c23-d725-9720-57ee0b8b14bc.log)

I think it would be best to run the actual launcher/installer if its present so the user doesn't get stuck due to unintuitive behaviour.

![image](https://user-images.githubusercontent.com/48480506/66747655-58d62100-ee85-11e9-9d39-f7955313d0a4.png)

Hope this helps.

**Comment by Haximaxi** [comment]
I got a similar issue it shows PoE as installed on the main page (while it is not) and no matter what i do it keeps showing it as installed there
![V2QR8QH - Imgur](https://user-images.githubusercontent.com/57035855/67618883-37662500-f7f5-11e9-92ed-0006315c0b93.png)
![IzuwBUY - Imgur](https://user-images.githubusercontent.com/57035855/67618885-3e8d3300-f7f5-11e9-8bd4-94c0d56932c9.png)
