### ISSUE TITLE
FOG Fork Autoupdate Request

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [nyash-qq/galaxy-plugin-poe#5]
Hey,

we're planning on creating a fork/autoupdate system with selected plugins. This would allow us to create a list of curated and reviewed plugins which could be of use to GOG Galaxy people.

Of course you will be credited as the creator and developer of the plugin in the fork readme and possibly other places.

Before we do that we need to ask you to create a fog_release branch which would contain only your plugin code, manifest.json and a requirements.txt file (without 3rdparty directories). For Github releases, we will include whole directory where manifest.json is placed and build dependencies directly there. This is for easier code verification. Code for repo synchronization can be found here: https://github.com/FriendsOfGalaxy/galaxy-integrations-updater

So in your case the branch would have an example structure of:

- src/your-python-files.py
- src/manifest.json
- requirements.txt
- README.md
- LICENSE

where requirements.txt contains the dependencies from your requirements-release.txt file

**Comment by into-the-intraverse** [comment]
I've updated that in ee021bb34e31488aaf14f1112c62623317e17e00, but please note the plugin is licensed with GPL-3.0, which is more restrictive than MIT license used in your repos and imposes some obligations on you.

**Comment by FriendsOfGalaxy** [comment]
Thanks. It was not exactly what I mean, so I've prepare PR https://github.com/nyash-qq/galaxy-plugin-poe/pull/6

> please note the plugin is licensed with GPL-3.0, which is more restrictive than MIT license used in your repos and imposes some obligations on you.

Sure. GPL-3.0 requires state changes but in principle we do not want to add any changes except Readme (that will points to your repo) and .github CI files (what doesn't interfere with the code itself). Example:
https://github.com/FriendsOfGalaxy/galaxy-integration-bethesda

Additionally we'll add Copyright statement:
```Copyright (C) 2019 nyash-qq```
Is it ok or maybe do you want to include your real name?
